module.exports = [
    "Boston College",
    "Boston University",
    "Brandeis University",
    "Brown University",
    "California Institute of Technology",
    "Carnegie Mellon University",
    "Case Western Reserve University",
    "Columbia University",
    "Cornell University",
    "Dartmouth College",
    "Emory University",
    "Georgetown University",
    "Georgia Institute of Technology",
    "Harvard University",
    "Johns Hopkins University",
    "Lehigh University",
    "MIT",
    "New York University",
    "Northeastern University",
    "Northwestern University",
    "Pepperdine University",
    "Princeton University",
    "Rice University",
    "Stanford University",
    "Tufts University",
    "Tulane",
    "UC Berkeley",
    "UCD",
    "UCI",
    "UCLA",
    "UCSB",
    "UCSD",
    "UIUC",
    "University of Chicago",
    "University of Florida",
    "University of Georgia",
    "University of Michigan -- Ann Arbor",
    "University of North Carolina -- Chapel Hill",
    "University of Notre Dame",
    "University of Pennsylvania",
    "University of Rochester",
    "University of Southern California",
    "University of Texas at Austin",
    "University of Virginia",
    "University of Wisconsin – Madison",
    "Vanderbilt University",
    "Wake Forest University",
    "Washington University in St. Louis",
    "William & Mary",
    "Yale University"
];